os: linux
language: java
jobs:
  include:
    - jdk: openjdk8
    - jdk: oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk12
    - jdk: oraclejdk12
env:
  global:
  - secure: hiAE0Gt7pcTmcQ/rjfK+KB+Mj1O3LaEM6wNgFleG04fuPbsUgTpF3U1HMTfEvU8nB0AEoIHgPZ2qWHIqGdJ23HfC7pTXtZXy8YSMOnPpTx8j9+qX0i7kJsqA6CNd+5i1CN0aM0uSd2CXRj7CFpwBa+5kfQmsml90oG3mev1MXcs=
  - # ^^SONATYPE_USERNAME
  - secure: Sa7tSlz29eOhOazmyGAfv7tFtaZjI1PMtgQJ3fFFZ2EVaAbxxGU/l+TVmcCOxOt7OdCf1MTgB9/dRGPZAuVdtelPIytoJEpB7U2qBci72K1at2zqKF6dq0pPswuwdbkqJeAf39M3J1nZcXKXwirU/J4OfwWyi5qwXpM8pO7W/qM=
  - # ^^SONATYPE_PASSWORD
  - GPG_KEY_NAME=C546418B
  - secure: fNOQPRDKEoW62EnxhXqb8q3JChwfYiUk6EidmXzvcEFQZutWmSnagPIwzywfeEt4FlLrhspLawtC5MIuFjOQY80S4oEkEAj28A1ltFb18upjN807fzSVFmo/3+j0r8geLpEfDc0qh4GIGhMz1WtfR1zFJ5YtNzN5wLKeF2/dB8M=
  - # ^^GPG_PASSPHRASE
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - ./travis/before-deploy.sh
  - cp ./travis/.m2.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  cleanup: false
  script: "if [ '${TRAVIS_JDK_VERSION}' = 'oraclejdk12' ]; then mvn deploy -P release -DskipTests=true ; fi"
  on:
    repo: thelinmichael/spotify-web-api-java
    branch:
    - master
    - v1
    tags: true
notifications:
  email:
    on_success: never
    on_failure: change
